"""
Official C2PA verification adapter.

This module keeps the optional c2pa-python dependency isolated from the
metadata detector. When c2pa-python is installed, it reads manifests through
the official C2PA SDK and asks the SDK to verify the manifest/signature chain.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable


AI_DIGITAL_SOURCE_MARKERS = {
    "trainedalgorithmicmedia",
    "compositewithtrainedalgorithmicmedia",
    "algorithmicmedia",
    "generated by ai",
    "ai generated",
    "adobe firefly",
    "google imagen",
    "synthid",
    "dall-e",
    "dalle",
    "midjourney",
    "stable diffusion",
}


@dataclass
class C2PAVerificationResult:
    available: bool
    has_manifest: bool = False
    verified: bool | None = None
    trusted: bool | None = None
    validation_state: str = ""
    validation_results: dict[str, Any] | None = None
    manifest_store: dict[str, Any] | None = None
    active_manifest: dict[str, Any] | None = None
    sdk_version: str = ""
    embedded: bool | None = None
    remote_url: str | None = None
    ai_markers: list[str] = field(default_factory=list)
    claim_generator: str = ""
    error: str = ""
    asset_format: str = ""
    extension_mismatch: bool = False
    validation_issues: list[str] = field(default_factory=list)

    @property
    def ai_generated(self) -> bool:
        return bool(self.ai_markers)

    def evidence_summary(self) -> str:
        if not self.has_manifest:
            if self.available:
                parts = ["No C2PA manifest found"]
                if self.asset_format:
                    parts.append(f"asset_format={self.asset_format}")
                if self.extension_mismatch:
                    parts.append("extension_mismatch=true")
                return "; ".join(parts)
            return self.error or "C2PA verifier unavailable"

        parts = ["C2PA manifest found"]
        if self.validation_state:
            parts.append(f"validation_state={self.validation_state}")
        if self.verified is not None:
            parts.append(f"signature_chain={'verified' if self.verified else 'failed'}")
        if self.trusted is not None:
            parts.append(f"trust={'trusted' if self.trusted else 'untrusted'}")
        if self.claim_generator:
            parts.append(f"claim_generator={self.claim_generator}")
        if self.ai_markers:
            parts.append("ai_markers=" + ",".join(self.ai_markers[:4]))
        if self.validation_issues:
            parts.append("validation_issues=" + ",".join(self.validation_issues[:4]))
        if self.remote_url:
            parts.append(f"remote_manifest={self.remote_url}")
        if self.sdk_version:
            parts.append(f"c2pa_sdk={self.sdk_version}")
        return "; ".join(parts)


def _iter_strings(value: Any) -> Iterable[str]:
    if isinstance(value, str):
        yield value
    elif isinstance(value, dict):
        for key, item in value.items():
            yield str(key)
            yield from _iter_strings(item)
    elif isinstance(value, list):
        for item in value:
            yield from _iter_strings(item)


def _find_ai_markers(manifest_store: dict[str, Any]) -> list[str]:
    found: list[str] = []
    seen = set()
    for text in _iter_strings(manifest_store):
        lowered = text.lower()
        for marker in AI_DIGITAL_SOURCE_MARKERS:
            if marker in lowered and marker not in seen:
                seen.add(marker)
                found.append(marker)
    return found


def _extract_claim_generator(active_manifest: dict[str, Any] | None) -> str:
    if not active_manifest:
        return ""

    claim_generator = active_manifest.get("claim_generator")
    if isinstance(claim_generator, str):
        return claim_generator
    if isinstance(claim_generator, dict):
        name = claim_generator.get("name") or claim_generator.get("identifier")
        version = claim_generator.get("version")
        if name and version:
            return f"{name} {version}"
        if name:
            return str(name)

    infos = active_manifest.get("claim_generator_info")
    if isinstance(infos, list) and infos:
        first = infos[0]
        if isinstance(first, dict):
            name = first.get("name") or first.get("identifier")
            version = first.get("version")
            if name and version:
                return f"{name} {version}"
            if name:
                return str(name)

    return ""


def _contains_failure(value: Any) -> bool:
    if isinstance(value, dict):
        for key, item in value.items():
            key_lower = str(key).lower()
            if key_lower in {"failure", "failures", "error", "errors"} and item:
                return True
            if _contains_failure(item):
                return True
    elif isinstance(value, list):
        for item in value:
            if _contains_failure(item):
                return True
    elif isinstance(value, str):
        lowered = value.lower()
        return any(token in lowered for token in ("invalid", "failure", "error", "untrusted"))
    return False


def _contains_trust_failure(value: Any) -> bool:
    if isinstance(value, dict):
        for key, item in value.items():
            key_lower = str(key).lower()
            if "trust" in key_lower and _contains_failure(item):
                return True
            if _contains_trust_failure(item):
                return True
    elif isinstance(value, list):
        for item in value:
            if _contains_trust_failure(item):
                return True
    elif isinstance(value, str):
        lowered = value.lower()
        return "trust" in lowered and any(token in lowered for token in ("invalid", "failure", "error", "untrusted"))
    return False


def _contains_non_trust_failure(value: Any) -> bool:
    if isinstance(value, dict):
        for key, item in value.items():
            key_lower = str(key).lower()
            if key_lower in {"failure", "failures", "error", "errors"} and item:
                if not _contains_only_trust_related(item):
                    return True
            if _contains_non_trust_failure(item):
                return True
    elif isinstance(value, list):
        for item in value:
            if _contains_non_trust_failure(item):
                return True
    elif isinstance(value, str):
        lowered = value.lower()
        if any(token in lowered for token in ("invalid", "failure", "error")):
            return "trust" not in lowered and "untrusted" not in lowered
    return False


def _contains_only_trust_related(value: Any) -> bool:
    strings = list(_iter_strings(value))
    if not strings:
        return False
    for text in strings:
        lowered = text.lower()
        if any(token in lowered for token in ("invalid", "failure", "error")):
            if "trust" not in lowered and "untrusted" not in lowered:
                return False
    return any("trust" in text.lower() or "untrusted" in text.lower() for text in strings)


def _contains_trust_signal(value: Any) -> bool:
    if isinstance(value, dict):
        for key, item in value.items():
            if "trust" in str(key).lower():
                return True
            if _contains_trust_signal(item):
                return True
    elif isinstance(value, list):
        for item in value:
            if _contains_trust_signal(item):
                return True
    elif isinstance(value, str):
        return "trust" in value.lower()
    return False


def _active_manifest_results(validation_results: dict[str, Any] | None) -> dict[str, Any] | None:
    if not isinstance(validation_results, dict):
        return None
    active = validation_results.get("activeManifest")
    return active if isinstance(active, dict) else None


def _has_validation_code(value: Any, code_fragment: str) -> bool:
    if isinstance(value, dict):
        code = value.get("code")
        if isinstance(code, str) and code_fragment in code:
            return True
        return any(_has_validation_code(item, code_fragment) for item in value.values())
    if isinstance(value, list):
        return any(_has_validation_code(item, code_fragment) for item in value)
    return False


def _collect_validation_issues(validation_results: dict[str, Any] | None) -> list[str]:
    issues: list[str] = []
    if not validation_results:
        return issues
    if _has_validation_code(validation_results, "ingredient.malformed"):
        issues.append("ingredient_malformed")
    if _has_validation_code(validation_results, "timeStamp.untrusted"):
        issues.append("timestamp_untrusted")
    return issues


def _verification_flags(validation_state: str, validation_results: dict[str, Any] | None) -> tuple[bool | None, bool | None]:
    state = (validation_state or "").lower()
    active_results = _active_manifest_results(validation_results) or validation_results
    has_failure = _contains_failure(active_results) if active_results else False
    has_non_trust_failure = _contains_non_trust_failure(active_results) if active_results else False
    has_trust_failure = _contains_trust_failure(active_results) if active_results else False
    has_trust_signal = _contains_trust_signal(active_results) if active_results else False
    active_signature_valid = _has_validation_code(active_results, "claimSignature.validated")
    active_data_hash_valid = _has_validation_code(active_results, "assertion.dataHash.match")

    verified: bool | None
    if active_signature_valid and active_data_hash_valid and not has_non_trust_failure:
        verified = True
    elif "valid" in state and "invalid" not in state and not has_non_trust_failure:
        verified = True
    elif "invalid" in state or (has_failure and has_non_trust_failure):
        verified = False
    else:
        verified = None

    trusted: bool | None
    if has_trust_failure:
        trusted = False
    elif verified is True and has_trust_signal:
        trusted = True
    else:
        trusted = None

    return verified, trusted


def _read_json(reader: Any) -> dict[str, Any]:
    raw = reader.json()
    if isinstance(raw, bytes):
        raw = raw.decode("utf-8", errors="replace")
    return json.loads(raw)


def _make_context(c2pa_module: Any) -> Any:
    settings = {
        "verify": {
            "verify_after_reading": True,
            "verify_trust": True,
            "verify_timestamp_trust": True,
            "ocsp_fetch": True,
            "remote_manifest_fetch": True,
        },
        "trust": {
            "verify_trust_list": True,
        },
    }
    context_cls = getattr(c2pa_module, "Context", None)
    if context_cls and hasattr(context_cls, "from_dict"):
        return context_cls.from_dict(settings)
    if hasattr(c2pa_module, "load_settings"):
        c2pa_module.load_settings(settings)
    return None


def _detect_asset_format(path: Path) -> tuple[str, bool]:
    suffix = path.suffix.lower()
    try:
        header = path.read_bytes()[:16]
    except OSError:
        return "", False

    asset_format = ""
    if header.startswith(b"\x89PNG\r\n\x1a\n"):
        asset_format = "png"
    elif header.startswith(b"\xff\xd8\xff"):
        asset_format = "jpeg"
    elif header[:4] == b"RIFF" and header[8:12] == b"WEBP":
        asset_format = "webp"

    expected_suffixes = {
        "png": {".png"},
        "jpeg": {".jpg", ".jpeg", ".jpe"},
        "webp": {".webp"},
    }
    mismatch = bool(asset_format and suffix and suffix not in expected_suffixes.get(asset_format, set()))
    return asset_format, mismatch


def verify_c2pa_file(image_path: str | Path) -> C2PAVerificationResult:
    path = Path(image_path)

    try:
        import c2pa
    except Exception as exc:
        return C2PAVerificationResult(
            available=False,
            error=f"c2pa-python unavailable: {exc}",
        )

    result = C2PAVerificationResult(available=True)
    try:
        result.asset_format, result.extension_mismatch = _detect_asset_format(path)
        result.sdk_version = str(c2pa.sdk_version()) if hasattr(c2pa, "sdk_version") else ""
        context = _make_context(c2pa)
        if result.extension_mismatch and result.asset_format:
            with path.open("rb") as stream:
                try:
                    reader = c2pa.Reader.try_create(result.asset_format, stream, None, context)
                except TypeError:
                    reader = c2pa.Reader.try_create(result.asset_format, stream)
        else:
            try:
                reader = c2pa.Reader.try_create(str(path), None, None, context)
            except TypeError:
                reader = c2pa.Reader.try_create(str(path))

        if reader is None:
            return result

        with reader:
            result.has_manifest = True
            result.manifest_store = _read_json(reader)
            result.validation_state = str(reader.get_validation_state() or "")
            result.validation_results = reader.get_validation_results() or None
            result.active_manifest = reader.get_active_manifest() or None
            result.embedded = bool(reader.is_embedded())
            result.remote_url = reader.get_remote_url() or None

        result.verified, result.trusted = _verification_flags(
            result.validation_state,
            result.validation_results,
        )
        result.validation_issues = _collect_validation_issues(result.validation_results)
        result.ai_markers = _find_ai_markers(result.manifest_store or {})
        result.claim_generator = _extract_claim_generator(result.active_manifest)
        return result

    except Exception as exc:
        result.error = str(exc)
        return result
