"""
Nephele Workshop - AI Validator Logic
Developer: ArisFusion Studio

核心功能：通过元数据分析检测图像是否为 AI 生成
"""

import re
import json
from pathlib import Path
from typing import Dict, Optional, List, Any, Tuple
from PIL import Image, ExifTags


class ValidatorError(Exception):
    """AI 鉴别器自定义异常"""
    pass


class MetaDataDetector:
    """
    Detects AI generation metadata from image files using heuristic analysis
    of EXIF, PNG info chunks, and generation parameters.
    """

    # 1. 明确的软件签名 (强特征，优先匹配专有字符串)
    # 顺序：Midjourney 先于 Gemini，以避免误判
    AI_SOFTWARE_SIGNATURES = {
        "Midjourney": [
            re.compile(r"job id:\s*[a-f0-9\-]+", re.IGNORECASE),  # 专有 Job ID
            re.compile(r"--ar\s*\d+:\d+", re.IGNORECASE),         # --ar 参数
            re.compile(r"--v\s*\d+", re.IGNORECASE),              # --v 参数
            re.compile(r"--stylize\s*\d+", re.IGNORECASE),        # --stylize
            re.compile(r"midjourney", re.IGNORECASE),             # 显式名称
            re.compile(r"mj v", re.IGNORECASE),
            re.compile(r"mj_", re.IGNORECASE),
        ],
        "ComfyUI": [
            re.compile(r"comfyui", re.IGNORECASE),
            re.compile(r"comfyland", re.IGNORECASE),
            # workflow/prompt JSON 在 detect 中单独处理
        ],
        "Gemini (Google)": [
            re.compile(r"gemini", re.IGNORECASE),
            re.compile(r"google deepmind", re.IGNORECASE),
            re.compile(r"generated by google", re.IGNORECASE),
            re.compile(r"google imagen", re.IGNORECASE),          # 必须有 "google"
            re.compile(r"imagen by google", re.IGNORECASE),
            re.compile(r"synthid", re.IGNORECASE),                # Google SynthID 水印
            re.compile(r"nano banana", re.IGNORECASE),            # 你的工具标识
            re.compile(r"nanobanana", re.IGNORECASE),
        ],
        "DALL-E": [re.compile(r"dall-e", re.IGNORECASE), re.compile(r"dalle", re.IGNORECASE)],
        "NovelAI": [re.compile(r"novelai", re.IGNORECASE), re.compile(r"nai-diffusion", re.IGNORECASE)],
        "InvokeAI": [re.compile(r"invokeai", re.IGNORECASE), re.compile(r"invoke ai", re.IGNORECASE)],
        "Fooocus": [re.compile(r"fooocus", re.IGNORECASE)],
        "Stable Diffusion": [re.compile(r"stable diffusion", re.IGNORECASE), re.compile(r"sd\.?next", re.IGNORECASE), re.compile(r"forge", re.IGNORECASE)],
        "Leonardo.ai": [re.compile(r"leonardo.ai", re.IGNORECASE)],
        "Adobe Firefly": [re.compile(r"adobe firefly", re.IGNORECASE)],
        "Bing Image Creator": [re.compile(r"bing image creator", re.IGNORECASE)],
    }

    # 2. 生成参数指纹 (次优先，当没有软件名时)
    # 移除 Gemini 专有，将 trainedAlgorithmicMedia 作为通用 AI 标记
    GENERATION_PARAM_FINGERPRINTS = [
        (r"Steps:\s*\d+", "Stable Diffusion (Parameters)"),
        (r"CFG scale:\s*[\d\.]+", "Stable Diffusion (Parameters)"),
        (r"Sampler:\s*\w+", "Stable Diffusion (Parameters)"),
        (r"Seed:\s*\d+", "Stable Diffusion (Parameters)"),
        (r"Model hash:\s*[a-f0-9]+", "Stable Diffusion (Parameters)"),
        (r"Model:\s*[^,\n]+", "Stable Diffusion (Parameters)"),
        (r"Negative prompt:", "Stable Diffusion (Parameters)"),
        (r"Size:\s*\d+x\d+", "Stable Diffusion (Parameters)"),
        (r"Clip skip:\s*\d+", "Stable Diffusion (Parameters)"),
        (r"Schedule type:\s*[^,\n]+", "Stable Diffusion (Parameters)"),
        (r"Denoising strength:\s*[\d\.]+", "Stable Diffusion (Parameters)"),
        (r"Hires upscale:\s*[\d\.]+", "Stable Diffusion (Parameters)"),
        # 更新 regex 以匹配 IPTC/XMP 变体（包括 URL）
        (r"DigitalSourceType\s*[:=]\s*(?:http://cv\.iptc\.org/newscodes/digitalsourcetype/)?trainedAlgorithmicMedia", "Generative AI (IPTC/XMP Standard)"),
    ]

    RAW_METADATA_SCAN_LIMIT = 128 * 1024 * 1024

    C2PA_CONTAINER_MARKERS = [
        b"c2pa",
        b"jumbf",
        b"content credentials",
        b"contentcredentials",
        b"contentauth",
    ]

    C2PA_AI_MARKERS = [
        b"trainedalgorithmicmedia",
        b"compositewithtrainedalgorithmicmedia",
        b"algorithmicmedia",
        b"generated by ai",
        b"ai generated",
        b"adobe firefly",
        b"google imagen",
        b"synthid",
        b"dall-e",
        b"dalle",
        b"midjourney",
        b"stable diffusion",
    ]

    def __init__(self):
        pass

    def _decode_metadata_bytes(self, data: bytes) -> str:
        """Best-effort decoding for embedded XMP/C2PA text inside binary assets."""
        if not data:
            return ""
        text = data.decode("utf-8", errors="ignore")
        if len(text.strip()) < 8:
            text = data.decode("latin-1", errors="ignore")
        return text

    def _metadata_value_to_text(self, value: Any) -> str:
        if isinstance(value, bytes):
            return value.decode("utf-8", errors="ignore")
        return str(value)

    def _json_loads(self, value: str) -> Any:
        try:
            return json.loads(value)
        except Exception:
            return None

    def _json_has_keys(self, value: Any, keys: set[str]) -> bool:
        if isinstance(value, dict):
            lowered = {str(key).lower() for key in value.keys()}
            if lowered.intersection(keys):
                return True
            return any(self._json_has_keys(item, keys) for item in value.values())
        if isinstance(value, list):
            return any(self._json_has_keys(item, keys) for item in value)
        return False

    def _detect_structured_generator_metadata(self, key: str, value: Any) -> Optional[Tuple[str, str]]:
        text = self._metadata_value_to_text(value)
        lowered_key = key.lower()
        lowered_text = text.lower()
        parsed = self._json_loads(text)

        if "invoke" in lowered_key or "invokeai" in lowered_text or "invoke ai" in lowered_text:
            return "InvokeAI", f"PNG Info '{key}': InvokeAI metadata"

        if "fooocus" in lowered_key or "fooocus" in lowered_text:
            return "Fooocus", f"PNG Info '{key}': Fooocus metadata"

        if "novelai" in lowered_text or "nai-diffusion" in lowered_text:
            return "NovelAI", f"PNG Info '{key}': NovelAI metadata"

        if isinstance(parsed, dict):
            has_generation_keys = self._json_has_keys(
                parsed,
                {"sampler", "sampler_name", "steps", "scale", "cfg_scale", "seed", "model", "model_hash", "uc"},
            )
            has_novelai_shape = self._json_has_keys(parsed, {"uc"}) and self._json_has_keys(parsed, {"sampler", "steps", "scale"})
            if has_novelai_shape:
                return "NovelAI", f"PNG Info '{key}': NovelAI generation JSON"

            if "invoke" in lowered_key and has_generation_keys:
                return "InvokeAI", f"PNG Info '{key}': InvokeAI generation JSON"

            if lowered_key in {"sd-metadata", "sd_metadata", "generation_data", "generation_data_formatted"} and has_generation_keys:
                return "Stable Diffusion", f"PNG Info '{key}': Stable Diffusion generation JSON"

        return None

    def _analyze_c2pa_bytes(self, data: bytes) -> Optional[Tuple[str, str]]:
        """Detect AI signals embedded in C2PA/JUMBF Content Credentials payloads."""
        if not data:
            return None

        lowered = data.lower()
        has_c2pa_container = any(marker in lowered for marker in self.C2PA_CONTAINER_MARKERS)
        if not has_c2pa_container:
            return None

        for marker in self.C2PA_AI_MARKERS:
            if marker in lowered:
                return "Generative AI (C2PA Content Credentials)", marker.decode("ascii", errors="ignore")

        text = self._decode_metadata_bytes(data)
        res = self._analyze_text(text, include_weak_markers=False)
        if res:
            tool, marker = res
            return tool, f"C2PA payload: {marker}"

        return None

    # PNG ancillary chunks that may carry metadata text. Skip IDAT/PLTE/etc.
    PNG_METADATA_CHUNKS = {b"tEXt", b"iTXt", b"zTXt", b"eXIf", b"iCCP", b"caBX", b"jumb"}
    # WebP RIFF chunks that may carry metadata.
    WEBP_METADATA_CHUNKS = {b"EXIF", b"XMP ", b"ICCP", b"JUMB"}

    def _extract_png_metadata(self, data: bytes) -> bytes:
        out = bytearray()
        pos = 8  # skip signature
        n = len(data)
        iend_end = n
        while pos + 12 <= n:
            try:
                length = int.from_bytes(data[pos:pos + 4], "big")
                chunk_type = data[pos + 4:pos + 8]
            except Exception:
                break
            data_end = pos + 8 + length
            if length < 0 or data_end + 4 > n:
                break
            if chunk_type in self.PNG_METADATA_CHUNKS:
                out.extend(data[pos + 8:data_end])
                out.append(0)
            if chunk_type == b"IEND":
                iend_end = data_end + 4
                break
            pos = data_end + 4  # skip CRC
        # Some pipelines append C2PA/JUMBF payloads after IEND. Include any
        # trailing bytes verbatim — they cannot be pixel data.
        if iend_end < n:
            out.extend(data[iend_end:])
        return bytes(out)

    def _extract_jpeg_metadata(self, data: bytes) -> bytes:
        out = bytearray()
        pos = 2  # skip SOI (FFD8)
        n = len(data)
        while pos + 4 <= n:
            if data[pos] != 0xFF:
                break
            # Skip fill bytes
            while pos < n and data[pos] == 0xFF:
                pos += 1
            if pos >= n:
                break
            marker = data[pos]
            pos += 1
            # Standalone markers without length payload
            if marker == 0xD9:  # EOI
                break
            if marker == 0xDA:  # SOS — compressed image data starts here
                break
            if marker == 0x00 or marker == 0x01 or 0xD0 <= marker <= 0xD8:
                continue
            if pos + 2 > n:
                break
            seg_len = int.from_bytes(data[pos:pos + 2], "big")
            if seg_len < 2 or pos + seg_len > n:
                break
            seg_data = data[pos + 2:pos + seg_len]
            # APP0..APP15 (E0..EF) and COM (FE) carry text-style metadata
            if 0xE0 <= marker <= 0xEF or marker == 0xFE:
                out.extend(seg_data)
                out.append(0)
            pos += seg_len
        return bytes(out)

    def _extract_webp_metadata(self, data: bytes) -> bytes:
        out = bytearray()
        n = len(data)
        if n < 12:
            return b""
        pos = 12  # skip RIFF + size + WEBP
        while pos + 8 <= n:
            fourcc = data[pos:pos + 4]
            size = int.from_bytes(data[pos + 4:pos + 8], "little")
            if size < 0 or pos + 8 + size > n:
                break
            if fourcc in self.WEBP_METADATA_CHUNKS:
                out.extend(data[pos + 8:pos + 8 + size])
                out.append(0)
            pos += 8 + size + (size & 1)  # chunks are padded to even size
        return bytes(out)

    def _extract_metadata_blocks(self, data: bytes) -> bytes:
        """
        Return bytes from text/metadata-bearing containers only, skipping
        pixel/compressed payloads. This prevents random regex hits in raw
        IDAT / SOS data from being mistaken for AI markers.
        """
        if data.startswith(b"\x89PNG\r\n\x1a\n"):
            return self._extract_png_metadata(data)
        if data[:2] == b"\xff\xd8":
            return self._extract_jpeg_metadata(data)
        if data[:4] == b"RIFF" and data[8:12] == b"WEBP":
            return self._extract_webp_metadata(data)
        # Unknown format: keep legacy behavior (whole file).
        return data

    def _scan_raw_metadata(self, image_path: Path) -> Tuple[Optional[Tuple[str, str]], bool]:
        """
        Scan only metadata-bearing chunks/segments of an image, not pixel data.

        C2PA manifests live in PNG `caBX`/`jumb` chunks or JPEG APP11 segments.
        Pillow may not surface them through Image.info, so we parse the
        container ourselves and feed only those bytes to the text analyzer.
        """
        try:
            size = image_path.stat().st_size
            if size > self.RAW_METADATA_SCAN_LIMIT:
                return None, False
            data = image_path.read_bytes()
        except OSError:
            return None, False

        metadata_bytes = self._extract_metadata_blocks(data)
        lowered = metadata_bytes.lower()
        has_c2pa_container = any(marker in lowered for marker in self.C2PA_CONTAINER_MARKERS)
        c2pa_res = self._analyze_c2pa_bytes(metadata_bytes)
        if c2pa_res:
            return c2pa_res, has_c2pa_container

        text = self._decode_metadata_bytes(metadata_bytes)
        return self._analyze_text(text, include_weak_markers=False), has_c2pa_container

    def _detect_google_visible_watermark(self, image_path: Path) -> bool:
        """
        Detect the visible Google/Gemini sparkle mark often placed near the
        lower-right area of generated images. This is visual evidence, not a
        SynthID decoder.
        """
        try:
            with Image.open(image_path) as img:
                img = img.convert("RGB")
                scale = 512 / max(img.size)
                if scale < 1:
                    img = img.resize((round(img.width * scale), round(img.height * scale)))

                width, height = img.size
                pix = img.load()
                mask = set()
                for y in range(height // 2, height):
                    for x in range(width // 2, width):
                        r, g, b = pix[x, y]
                        saturation = max(r, g, b) - min(r, g, b)
                        luminance = (r * 299 + g * 587 + b * 114) // 1000
                        if 110 <= luminance <= 245 and saturation < 28:
                            if not (luminance > 235 and saturation < 8):
                                mask.add((x, y))

                seen = set()
                for pt in list(mask):
                    if pt in seen:
                        continue
                    stack = [pt]
                    seen.add(pt)
                    xs = []
                    ys = []
                    while stack:
                        x, y = stack.pop()
                        xs.append(x)
                        ys.append(y)
                        for nx in (x - 1, x, x + 1):
                            for ny in (y - 1, y, y + 1):
                                npt = (nx, ny)
                                if npt in mask and npt not in seen:
                                    seen.add(npt)
                                    stack.append(npt)

                    area = len(xs)
                    min_x, max_x = min(xs), max(xs)
                    min_y, max_y = min(ys), max(ys)
                    comp_w = max_x - min_x + 1
                    comp_h = max_y - min_y + 1
                    center_x = (min_x + max_x) / 2
                    center_y = (min_y + max_y) / 2
                    density = area / max(1, comp_w * comp_h)

                    if not (80 <= area <= 900):
                        continue
                    if not (14 <= comp_w <= 60 and 14 <= comp_h <= 80):
                        continue
                    if not (0.12 <= density <= 0.70):
                        continue
                    if center_x < width * 0.62 or center_y < height * 0.55:
                        continue

                    # A sparkle mark has a sparse center-heavy diamond shape.
                    mid_x = (min_x + max_x) / 2
                    mid_y = (min_y + max_y) / 2
                    near_center = sum(
                        1 for x, y in zip(xs, ys)
                        if abs(x - mid_x) <= comp_w * 0.25 and abs(y - mid_y) <= comp_h * 0.25
                    )
                    if near_center / area >= 0.18:
                        return True
        except Exception:
            return False

        return False

    def _analyze_text(self, text: str, include_weak_markers: bool = True) -> Optional[Tuple[str, str]]:
        """
        Analyze a string for AI markers.
        Returns: (tool_name, found_marker) or None
        
        检测优先级：
        1. 先检查明确的软件签名（使用 regex 更严格匹配）
        2. 再检查生成参数指纹（如果 IPTC 标记，检查是否有 Google 证据，否则通用）
        """
        if not text:
            return None
        
        text_lower = text.lower()

        # 1. Check Explicit Software Names (按字典顺序，Midjourney 先)
        weak_patterns = {r"mj_"}
        for tool, patterns in self.AI_SOFTWARE_SIGNATURES.items():
            for pattern in patterns:
                if not include_weak_markers and pattern.pattern in weak_patterns:
                    continue
                if pattern.search(text_lower):
                    return tool, pattern.pattern

        # 2. Check Generation Parameter Fingerprints
        match_count = 0
        evidence = []
        detected_tool = None
        weak_evidence_found = []
        for pattern, tool_name in self.GENERATION_PARAM_FINGERPRINTS:
            match = re.search(pattern, text, re.IGNORECASE)
            if match:
                if "IPTC/XMP Standard" in tool_name:
                    # 如果是通用 IPTC，检查是否有 Google 证据
                    if any(re.search(p, text_lower) for p in self.AI_SOFTWARE_SIGNATURES["Gemini (Google)"]):
                        return "Gemini (Google)", "IPTC/XMP with Google Evidence"
                    else:
                        detected_tool = "Generative AI (Unknown)"
                        evidence.append("IPTC/XMP Signature")
                else:
                    match_count += 1
                    evidence.append(pattern)
        
        if match_count >= 1:
            return "Stable Diffusion WebUI", "Generation Parameters Detected"

        if detected_tool:
            return detected_tool, "; ".join(evidence)

        return None

    def detect(self, image_path: str) -> Dict[str, str]:
        """
        检测图像文件中的 AI 生成元数据
        
        Args:
            image_path: 图像文件路径
            
        Returns:
            检测结果字典，包含：
            - status: "ai" | "human" | "error"
            - reason: 检测原因描述
            - tool: 检测到的 AI 工具名称（如果为 AI）
            - evidence: 证据描述
        """
        img_path = Path(image_path)
        if not img_path.exists():
            return {"status": "error", "reason": "文件不存在", "tool": "", "evidence": ""}

        evidence_found = []
        weak_evidence_found = []
        context_evidence_found = []
        detected_tool = None
        extension_mismatch = False
        minimal_web_jpeg = False
        
        try:
            with Image.open(img_path) as img:
                img.load()  # Ensure header is loaded
                actual_format = (img.format or "").upper()
                suffix = img_path.suffix.lower()
                if actual_format == "JPEG" and suffix not in {".jpg", ".jpeg", ".jpe"}:
                    extension_mismatch = True
                    context_evidence_found.append(f"File extension mismatch: {suffix} file contains JPEG data")
                elif actual_format == "PNG" and suffix != ".png":
                    extension_mismatch = True
                    context_evidence_found.append(f"File extension mismatch: {suffix} file contains PNG data")

                minimal_jpeg_keys = {"jfif", "jfif_density", "jfif_unit", "jfif_version", "progression", "progressive"}
                if actual_format == "JPEG" and set(img.info.keys()).issubset(minimal_jpeg_keys):
                    minimal_web_jpeg = True
                    context_evidence_found.append("Minimal JPEG metadata only")

                # --- 1. Check PNG Info / tEXt chunks ---
                if hasattr(img, 'info') and img.info:
                    software_value = img.info.get("Software") or img.info.get("software")
                    if isinstance(software_value, bytes):
                        software_text = software_value.decode("utf-8", errors="ignore")
                    else:
                        software_text = str(software_value or "")
                    software_lower = software_text.lower()
                    if "celsys" in software_lower or "clip studio" in software_lower:
                        context_evidence_found.append("Edited/exported by CELSYS/Clip Studio Paint")

                    if not detected_tool:
                        for key, val in img.info.items():
                            if not isinstance(val, (str, bytes)):
                                continue
                            structured_res = self._detect_structured_generator_metadata(key, val)
                            if structured_res:
                                detected_tool, marker = structured_res
                                evidence_found.append(marker)
                                break

                    # Case A: A1111 / SD
                    if 'parameters' in img.info:
                        val = img.info['parameters']
                        if isinstance(val, str) and ("Steps:" in val or "Prompt" in val):
                            detected_tool = "Stable Diffusion (A1111)"
                            evidence_found.append("Stable Diffusion parameters chunk")
                            res = self._analyze_text(val)
                            if res: 
                                detected_tool, marker = res
                                evidence_found.append(f"Parameters: {marker}")

                    # Case B: ComfyUI (专有检查)
                    if not detected_tool and ('workflow' in img.info or 'prompt' in img.info):
                        # 验证是否是 JSON
                        try:
                            if 'workflow' in img.info:
                                json.loads(img.info['workflow'])
                                evidence_found.append("Valid 'workflow' JSON")
                            if 'prompt' in img.info:
                                json.loads(img.info['prompt'])
                                evidence_found.append("Valid 'prompt' JSON")
                            detected_tool = "ComfyUI"
                        except json.JSONDecodeError:
                            pass  # 非 JSON，忽略

                    # Case C: Generic Scan (其他 info)
                    if not detected_tool:
                        for key, val in img.info.items():
                            if isinstance(val, (str, bytes)):
                                val_str = self._metadata_value_to_text(val)
                                res = self._analyze_text(val_str)
                                if res:
                                    detected_tool, marker = res
                                    evidence_found.append(f"PNG Info '{key}': {marker}")
                                    break

                    for key, val in img.info.items():
                        if not isinstance(val, (str, bytes)):
                            continue
                        val_str = val.decode("utf-8", errors="ignore") if isinstance(val, bytes) else str(val)
                        if "DigitalSourceType" in val_str and "trainedAlgorithmicMedia" in val_str:
                            marker = f"PNG Info '{key}': IPTC/XMP trainedAlgorithmicMedia"
                            if marker not in evidence_found:
                                evidence_found.append(marker)

                # --- 2. Check EXIF / XMP Data ---
                if not detected_tool:
                    exif = img.getexif()
                    if exif:
                        for tag_id, value in exif.items():
                            tag_name = ExifTags.TAGS.get(tag_id, str(tag_id))
                            
                            # Handle UserComment or other bytes
                            if isinstance(value, bytes):
                                try:
                                    value_str = value.decode('utf-8', errors='ignore')
                                except:
                                    continue
                            else:
                                value_str = str(value)

                            res = self._analyze_text(value_str)
                            if res:
                                detected_tool, marker = res
                                evidence_found.append(f"EXIF {tag_name}: {marker}")
                                break

        except Exception as e:
            return {"status": "error", "reason": f"读取错误: {str(e)}", "tool": "", "evidence": ""}

        # --- 3. Official C2PA manifest/signature verification ---
        c2pa_available = False
        c2pa_has_manifest = False
        c2pa_claim_generator = ""
        try:
            from tools.validator.c2pa_verifier import verify_c2pa_file

            c2pa_result = verify_c2pa_file(img_path)
            c2pa_available = c2pa_result.available
            if c2pa_result.has_manifest:
                c2pa_has_manifest = True
                c2pa_claim_generator = c2pa_result.claim_generator or ""
                evidence_found.append(c2pa_result.evidence_summary())
                if c2pa_result.ai_generated:
                    detected_tool = "Generative AI (C2PA Content Credentials)"
            elif c2pa_result.available and c2pa_result.error:
                evidence_found.append(f"C2PA verification error: {c2pa_result.error}")
            elif c2pa_result.available:
                evidence_found.append("No C2PA manifest found")
        except Exception as e:
            evidence_found.append(f"C2PA verification error: {e}")

        # --- 4. Raw metadata fallback: C2PA/JUMBF/XMP payloads ---
        if not detected_tool and not c2pa_has_manifest:
            res, has_c2pa_container = self._scan_raw_metadata(img_path)
            if res:
                detected_tool, marker = res
                prefix = "Raw metadata"
                if not c2pa_available and has_c2pa_container:
                    prefix = "Raw metadata (official C2PA verifier unavailable)"
                evidence_found.append(f"{prefix}: {marker}")
            elif has_c2pa_container:
                if c2pa_available:
                    evidence_found.append("C2PA Content Credentials found, no AI generation marker")
                else:
                    evidence_found.append("C2PA Content Credentials found, official verifier unavailable")

        # --- 5. Visible Google/Gemini watermark ---
        google_context = "google" in c2pa_claim_generator.lower()
        filename_lower = img_path.name.lower()
        filename_gemini_hint = "gemini" in filename_lower or "google" in filename_lower
        if not detected_tool and (google_context or filename_gemini_hint):
            if self._detect_google_visible_watermark(img_path):
                detected_tool = "Gemini (Google Visible Watermark)"
                evidence_found.append("Visible watermark: Google/Gemini sparkle mark")

        # --- 6. Final Fallback: Filename Check ---
        if not detected_tool:
            res = self._analyze_text(filename_lower, include_weak_markers=False)
            if res:
                weak_tool, marker = res
                if c2pa_has_manifest:
                    weak_evidence_found.append(f"Filename suggests {weak_tool}: {marker}")
                else:
                    weak_evidence_found.append(f"Filename suggests {weak_tool}: {marker}")

        if extension_mismatch and minimal_web_jpeg:
            context_evidence_found.append("Downloaded file appears re-encoded or metadata-stripped")

        # --- Result Construction ---
        if detected_tool:
            return {
                "status": "ai",
                "reason": f"检测到 {detected_tool} 元数据",
                "tool": detected_tool,
                "evidence": "; ".join(evidence_found + context_evidence_found)
            }
        else:
            if weak_evidence_found:
                return {
                    "status": "unknown",
                    "reason": "AI indicators found, but C2PA credentials do not declare AI generation",
                    "tool": "",
                    "evidence": "; ".join(evidence_found + context_evidence_found + weak_evidence_found)
                }
            reason = "C2PA Content Credentials do not declare AI generation" if c2pa_has_manifest else "No known AI generation metadata detected"
            return {
                "status": "human",
                "reason": reason,
                "tool": "",
                "evidence": "; ".join(evidence_found + context_evidence_found) if evidence_found or context_evidence_found else "No metadata signatures found"
            }
